# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint to retrieve high-level match stats for Firestone users

Globals:
    Api:
        # API Gateway regional endpoints
        EndpointConfiguration: EDGE
        Cors:
            AllowMethods: "'*'"
            AllowHeaders: "'*'"
            AllowOrigin: "'*'"
        MinimumCompressionSize: 100

Resources:
    ProcessMatchStatsFunction2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: retrieve-overview-match-stats.default
            # Runtime: nodejs8.10
            Runtime: nodejs16.x
            Timeout: 800
            ReservedConcurrentExecutions: 80
            MemorySize: 512 # Need to increase the memory to go faster and avoid the 30s timeout on the API gateway
            CodeUri: ./dist/retrieve-overview-match-stats
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-retrieve-user-match-stats-2
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE