# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint to retrieve high-level match stats for Firestone users

Globals:
    Api:
        # API Gateway regional endpoints
        EndpointConfiguration: EDGE
        Cors:
            AllowMethods: "'*'"
            AllowHeaders: "'*'"
            AllowOrigin: "'*'"
        MinimumCompressionSize: 100

Resources:
    ProcessMatchStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: retrieve-overview-match-stats.default
            # Runtime: nodejs8.10
            Runtime: nodejs10.x
            Timeout: 60
            ReservedConcurrentExecutions: 40
            MemorySize: 128 # Need to increase the memory to go faster and avoid the 30s timeout on the API gateway
            CodeUri: ./dist/retrieve-overview-match-stats
            # https://stackoverflow.com/questions/39144688/aws-lambda-invoke-not-calling-another-lambda-function-node-js
            # VpcConfig:
            #     SecurityGroupIds:
            #         - sg-0ed63616362bf1a30
            #     SubnetIds:
            #         - subnet-0b36da5c19637a351
            #         - subnet-0b730ca9af74a95dd
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-retrieve-user-match-stats
            Events:
                GetMatchStatsResource:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: any

Outputs:
    ProcessMatchStatsApi:
        Description: URL to retrieve match stats for Firestone users
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/matchStats'
        Export:
            Name: ProcessMatchStatsApi
